# Generated by Django 5.2.1 on 2025-05-24 17:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("product", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="姓名")),
                (
                    "phone",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="手机号码"
                    ),
                ),
                (
                    "customer_type",
                    models.CharField(
                        choices=[
                            ("regular", "普通顾客"),
                            ("member", "会员"),
                            ("vip", "VIP会员"),
                        ],
                        default="regular",
                        max_length=10,
                        verbose_name="客户类型",
                    ),
                ),
                (
                    "member_code",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        unique=True,
                        verbose_name="会员号",
                    ),
                ),
                (
                    "birth_date",
                    models.DateField(blank=True, null=True, verbose_name="生日"),
                ),
                ("points", models.IntegerField(default=0, verbose_name="积分")),
                (
                    "total_consumption",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="累计消费",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="是否激活"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "客户",
                "verbose_name_plural": "客户",
                "ordering": ["member_code"],
            },
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order_number",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="订单编号"
                    ),
                ),
                (
                    "order_type",
                    models.CharField(
                        choices=[("dine_in", "堂食"), ("takeaway", "外带")],
                        default="dine_in",
                        max_length=10,
                        verbose_name="订单类型",
                    ),
                ),
                (
                    "order_date",
                    models.DateTimeField(auto_now_add=True, verbose_name="订单日期"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待处理"),
                            ("processing", "制作中"),
                            ("completed", "已完成"),
                            ("cancelled", "已取消"),
                        ],
                        default="pending",
                        max_length=10,
                        verbose_name="订单状态",
                    ),
                ),
                (
                    "subtotal",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="商品小计",
                    ),
                ),
                (
                    "discount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="折扣金额",
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="订单总金额",
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("cash", "现金"),
                            ("wechat", "微信"),
                            ("alipay", "支付宝"),
                            ("card", "银行卡"),
                            ("member_card", "会员卡"),
                        ],
                        max_length=15,
                        verbose_name="支付方式",
                    ),
                ),
                (
                    "payment_status",
                    models.BooleanField(default=False, verbose_name="支付状态"),
                ),
                (
                    "payment_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="支付时间"
                    ),
                ),
                ("cashier", models.CharField(max_length=50, verbose_name="收银员")),
                ("notes", models.TextField(blank=True, null=True, verbose_name="备注")),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="orders",
                        to="sales.customer",
                        verbose_name="客户",
                    ),
                ),
            ],
            options={
                "verbose_name": "订单",
                "verbose_name_plural": "订单",
                "ordering": ["-order_date"],
            },
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.IntegerField(default=1, verbose_name="数量")),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="单价"
                    ),
                ),
                (
                    "subtotal",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="小计"
                    ),
                ),
                (
                    "discount",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=10, verbose_name="折扣"
                    ),
                ),
                (
                    "notes",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="备注"
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="sales.order",
                        verbose_name="订单",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="product.product",
                        verbose_name="商品",
                    ),
                ),
            ],
            options={
                "verbose_name": "订单项目",
                "verbose_name_plural": "订单项目",
            },
        ),
        migrations.CreateModel(
            name="DrinkTicket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ticket_number",
                    models.CharField(
                        max_length=30, unique=True, verbose_name="饮品票编号"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("waiting", "等待制作"),
                            ("making", "制作中"),
                            ("completed", "已完成"),
                            ("delivered", "已交付"),
                        ],
                        default="waiting",
                        max_length=10,
                        verbose_name="状态",
                    ),
                ),
                (
                    "barista",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="制作人员"
                    ),
                ),
                (
                    "start_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="开始制作时间"
                    ),
                ),
                (
                    "complete_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="完成时间"
                    ),
                ),
                (
                    "notes",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="备注"
                    ),
                ),
                (
                    "order_item",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="drink_ticket",
                        to="sales.orderitem",
                        verbose_name="订单项目",
                    ),
                ),
            ],
            options={
                "verbose_name": "饮品票",
                "verbose_name_plural": "饮品票",
            },
        ),
        migrations.CreateModel(
            name="Receipt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "receipt_number",
                    models.CharField(
                        max_length=30, unique=True, verbose_name="小票编号"
                    ),
                ),
                (
                    "printed",
                    models.BooleanField(default=False, verbose_name="是否已打印"),
                ),
                (
                    "print_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="打印时间"
                    ),
                ),
                (
                    "order",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="receipt",
                        to="sales.order",
                        verbose_name="订单",
                    ),
                ),
            ],
            options={
                "verbose_name": "小票",
                "verbose_name_plural": "小票",
            },
        ),
    ]
