# Generated by Django 5.2.1 on 2025-05-26 12:47

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customer",
            options={
                "managed": True,
                "ordering": ["name"],
                "verbose_name": "客户",
                "verbose_name_plural": "客户",
            },
        ),
        migrations.AlterModelOptions(
            name="drinkticket",
            options={
                "managed": True,
                "ordering": ["status", "created_at"],
                "verbose_name": "饮品票",
                "verbose_name_plural": "饮品票",
            },
        ),
        migrations.AlterModelOptions(
            name="order",
            options={
                "managed": False,
                "ordering": ["-created_at"],
                "verbose_name": "订单",
                "verbose_name_plural": "订单",
            },
        ),
        migrations.AlterModelOptions(
            name="orderitem",
            options={
                "managed": False,
                "verbose_name": "订单项",
                "verbose_name_plural": "订单项",
            },
        ),
        migrations.AlterModelOptions(
            name="receipt",
            options={
                "managed": True,
                "ordering": ["-created_at"],
                "verbose_name": "小票",
                "verbose_name_plural": "小票",
            },
        ),
        migrations.RemoveField(
            model_name="customer",
            name="birth_date",
        ),
        migrations.AddField(
            model_name="customer",
            name="address",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="customer",
            name="birthday",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="customer",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="drinkticket",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="receipt",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="customer",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="customer",
            name="customer_type",
            field=models.CharField(
                choices=[
                    ("regular", "普通顾客"),
                    ("member", "会员"),
                    ("vip", "VIP会员"),
                    ("wholesale", "批发客户"),
                ],
                default="regular",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="customer",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="customer",
            name="member_code",
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="customer",
            name="name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="customer",
            name="phone",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="customer",
            name="points",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="customer",
            name="total_consumption",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name="customer",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="drinkticket",
            name="barista",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="drinkticket",
            name="complete_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="drinkticket",
            name="id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="drinkticket",
            name="notes",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="drinkticket",
            name="order_item",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="drink_ticket",
                to="sales.orderitem",
            ),
        ),
        migrations.AlterField(
            model_name="drinkticket",
            name="start_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="drinkticket",
            name="status",
            field=models.CharField(
                choices=[
                    ("waiting", "等待制作"),
                    ("making", "制作中"),
                    ("completed", "已完成"),
                    ("delivered", "已交付"),
                    ("cancelled", "已取消"),
                ],
                default="waiting",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="drinkticket",
            name="ticket_number",
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name="receipt",
            name="id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="receipt",
            name="order",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="receipt",
                to="sales.order",
            ),
        ),
        migrations.AlterField(
            model_name="receipt",
            name="print_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="receipt",
            name="printed",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="receipt",
            name="receipt_number",
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterModelTable(
            name="customer",
            table="customers",
        ),
        migrations.AlterModelTable(
            name="drinkticket",
            table="drink_tickets",
        ),
        migrations.AlterModelTable(
            name="receipt",
            table="receipts",
        ),
    ]
