# Generated by Django 5.2.1 on 2025-05-26 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0002_alter_customer_options_alter_drinkticket_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="order",
            options={
                "managed": True,
                "ordering": ["-created_at"],
                "verbose_name": "订单",
                "verbose_name_plural": "订单",
            },
        ),
        migrations.AlterModelOptions(
            name="orderitem",
            options={
                "managed": True,
                "verbose_name": "订单项",
                "verbose_name_plural": "订单项",
            },
        ),
    ]
