# Generated by Django 5.2.1 on 2025-05-24 17:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("product", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Supplier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="供应商名称")),
                (
                    "supplier_code",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="供应商编码"
                    ),
                ),
                (
                    "contact_person",
                    models.CharField(max_length=50, verbose_name="联系人"),
                ),
                ("phone", models.CharField(max_length=20, verbose_name="联系电话")),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, null=True, verbose_name="电子邮箱"
                    ),
                ),
                ("address", models.TextField(verbose_name="地址")),
                (
                    "bank_account",
                    models.CharField(
                        blank=True, max_length=30, null=True, verbose_name="银行账号"
                    ),
                ),
                (
                    "bank_name",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="开户行"
                    ),
                ),
                (
                    "tax_id",
                    models.CharField(
                        blank=True, max_length=30, null=True, verbose_name="税号"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="是否激活"),
                ),
                ("notes", models.TextField(blank=True, null=True, verbose_name="备注")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "供应商",
                "verbose_name_plural": "供应商",
                "ordering": ["supplier_code"],
            },
        ),
        migrations.CreateModel(
            name="PurchaseOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order_number",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="订单编号"
                    ),
                ),
                ("order_date", models.DateField(verbose_name="订单日期")),
                (
                    "expected_delivery_date",
                    models.DateField(verbose_name="预计交货日期"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "草稿"),
                            ("submitted", "已提交"),
                            ("confirmed", "已确认"),
                            ("partially_received", "部分入库"),
                            ("fully_received", "全部入库"),
                            ("closed", "已关闭"),
                            ("cancelled", "已取消"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="订单状态",
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="订单总金额",
                    ),
                ),
                (
                    "payment_terms",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="付款条件"
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True, verbose_name="备注")),
                ("created_by", models.CharField(max_length=50, verbose_name="创建人")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="purchase_orders",
                        to="procurement.supplier",
                        verbose_name="供应商",
                    ),
                ),
            ],
            options={
                "verbose_name": "采购订单",
                "verbose_name_plural": "采购订单",
                "ordering": ["-order_date", "order_number"],
            },
        ),
        migrations.CreateModel(
            name="PurchaseOrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="数量"
                    ),
                ),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="单价"
                    ),
                ),
                (
                    "subtotal",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="小计"
                    ),
                ),
                (
                    "received_quantity",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="已入库数量",
                    ),
                ),
                (
                    "notes",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="备注"
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="product.product",
                        verbose_name="商品",
                    ),
                ),
                (
                    "purchase_order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="procurement.purchaseorder",
                        verbose_name="采购订单",
                    ),
                ),
            ],
            options={
                "verbose_name": "采购订单项目",
                "verbose_name_plural": "采购订单项目",
                "unique_together": {("purchase_order", "product")},
            },
        ),
        migrations.CreateModel(
            name="SupplierProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "supplier_product_code",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="供应商商品编码",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="合同价格"
                    ),
                ),
                (
                    "min_order_quantity",
                    models.DecimalField(
                        decimal_places=2,
                        default=1,
                        max_digits=10,
                        verbose_name="最小订购量",
                    ),
                ),
                (
                    "lead_time_days",
                    models.IntegerField(default=1, verbose_name="交货周期(天)"),
                ),
                (
                    "is_preferred",
                    models.BooleanField(default=False, verbose_name="是否首选供应商"),
                ),
                (
                    "contract_start_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="合同开始日期"
                    ),
                ),
                (
                    "contract_end_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="合同结束日期"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="suppliers",
                        to="product.product",
                        verbose_name="商品",
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="supplied_products",
                        to="procurement.supplier",
                        verbose_name="供应商",
                    ),
                ),
            ],
            options={
                "verbose_name": "供应商商品",
                "verbose_name_plural": "供应商商品",
                "unique_together": {("supplier", "product")},
            },
        ),
    ]
