# Generated by Django 5.2.1 on 2025-05-26 12:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("procurement", "0001_initial"),
        ("product", "0002_inventorylevel_alter_category_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="purchaseorder",
            options={
                "managed": True,
                "ordering": ["-order_date", "order_number"],
                "verbose_name": "采购订单",
                "verbose_name_plural": "采购订单",
            },
        ),
        migrations.AlterModelOptions(
            name="purchaseorderitem",
            options={
                "managed": True,
                "verbose_name": "采购订单项",
                "verbose_name_plural": "采购订单项",
            },
        ),
        migrations.AlterModelOptions(
            name="supplier",
            options={
                "managed": False,
                "ordering": ["name"],
                "verbose_name": "供应商",
                "verbose_name_plural": "供应商",
            },
        ),
        migrations.AlterModelOptions(
            name="supplierproduct",
            options={
                "managed": True,
                "verbose_name": "供应商产品",
                "verbose_name_plural": "供应商产品",
            },
        ),
        migrations.AlterUniqueTogether(
            name="purchaseorderitem",
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name="purchaseorder",
            name="id",
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="order_id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name="purchaseorderitem",
            name="item_id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="purchaseorder",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="purchaseorder",
            name="created_by",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="purchaseorder",
            name="expected_delivery_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="purchaseorder",
            name="notes",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="purchaseorder",
            name="order_date",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="purchaseorder",
            name="order_number",
            field=models.CharField(max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name="purchaseorder",
            name="payment_terms",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="purchaseorder",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "草稿"),
                    ("submitted", "已提交"),
                    ("approved", "已批准"),
                    ("rejected", "已拒绝"),
                    ("ordered", "已下单"),
                    ("partially_received", "部分收货"),
                    ("fully_received", "完全收货"),
                    ("cancelled", "已取消"),
                    ("closed", "已关闭"),
                ],
                default="draft",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="purchaseorder",
            name="supplier",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="procurement.supplier"
            ),
        ),
        migrations.AlterField(
            model_name="purchaseorder",
            name="total_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="purchaseorder",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="purchaseorderitem",
            name="notes",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="purchaseorderitem",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="product.product"
            ),
        ),
        migrations.AlterField(
            model_name="purchaseorderitem",
            name="purchase_order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="procurement.purchaseorder",
            ),
        ),
        migrations.AlterField(
            model_name="purchaseorderitem",
            name="quantity",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name="purchaseorderitem",
            name="received_quantity",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="purchaseorderitem",
            name="subtotal",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name="purchaseorderitem",
            name="unit_price",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name="supplierproduct",
            name="contract_end_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="supplierproduct",
            name="contract_start_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="supplierproduct",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="supplierproduct",
            name="id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="supplierproduct",
            name="is_preferred",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="supplierproduct",
            name="lead_time_days",
            field=models.IntegerField(default=7),
        ),
        migrations.AlterField(
            model_name="supplierproduct",
            name="min_order_quantity",
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
        ),
        migrations.AlterField(
            model_name="supplierproduct",
            name="price",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name="supplierproduct",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="suppliers",
                to="product.product",
            ),
        ),
        migrations.AlterField(
            model_name="supplierproduct",
            name="supplier",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="products",
                to="procurement.supplier",
            ),
        ),
        migrations.AlterField(
            model_name="supplierproduct",
            name="supplier_product_code",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="supplierproduct",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterModelTable(
            name="purchaseorder",
            table="purchase_orders",
        ),
        migrations.AlterModelTable(
            name="purchaseorderitem",
            table="purchase_order_items",
        ),
        migrations.AlterModelTable(
            name="supplierproduct",
            table="supplier_products",
        ),
        migrations.RemoveField(
            model_name="purchaseorderitem",
            name="id",
        ),
    ]
