# Generated by Django 5.2.1 on 2025-05-24 17:42

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("procurement", "0001_initial"),
        ("product", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="InventoryCount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "count_number",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="盘点单号"
                    ),
                ),
                ("count_date", models.DateField(verbose_name="盘点日期")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "草稿"),
                            ("in_progress", "进行中"),
                            ("completed", "已完成"),
                            ("cancelled", "已取消"),
                        ],
                        default="draft",
                        max_length=15,
                        verbose_name="状态",
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True, verbose_name="备注")),
                ("created_by", models.CharField(max_length=50, verbose_name="创建人")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="完成时间"
                    ),
                ),
            ],
            options={
                "verbose_name": "库存盘点",
                "verbose_name_plural": "库存盘点",
                "ordering": ["-count_date"],
            },
        ),
        migrations.CreateModel(
            name="Inventory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "current_quantity",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="当前库存量",
                    ),
                ),
                (
                    "minimum_quantity",
                    models.DecimalField(
                        decimal_places=2,
                        default=10,
                        max_digits=10,
                        verbose_name="最低库存量",
                    ),
                ),
                (
                    "maximum_quantity",
                    models.DecimalField(
                        decimal_places=2,
                        default=100,
                        max_digits=10,
                        verbose_name="最高库存量",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "product",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inventory",
                        to="product.product",
                        verbose_name="商品",
                    ),
                ),
            ],
            options={
                "verbose_name": "库存",
                "verbose_name_plural": "库存",
            },
        ),
        migrations.CreateModel(
            name="InventoryBatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "batch_number",
                    models.CharField(max_length=30, unique=True, verbose_name="批次号"),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="数量"
                    ),
                ),
                (
                    "remaining_quantity",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="剩余数量"
                    ),
                ),
                (
                    "cost_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="成本价"
                    ),
                ),
                (
                    "production_date",
                    models.DateField(blank=True, null=True, verbose_name="生产日期"),
                ),
                ("expiry_date", models.DateField(verbose_name="过期日期")),
                ("notes", models.TextField(blank=True, null=True, verbose_name="备注")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inventory_batches",
                        to="product.product",
                        verbose_name="商品",
                    ),
                ),
                (
                    "purchase_order_item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="inventory_batches",
                        to="procurement.purchaseorderitem",
                        verbose_name="采购订单项",
                    ),
                ),
            ],
            options={
                "verbose_name": "库存批次",
                "verbose_name_plural": "库存批次",
                "ordering": ["expiry_date", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="InventoryTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("purchase", "采购入库"),
                            ("sales", "销售出库"),
                            ("return", "退货入库"),
                            ("loss", "损耗出库"),
                            ("adjustment", "库存调整"),
                        ],
                        max_length=10,
                        verbose_name="交易类型",
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="数量"
                    ),
                ),
                (
                    "unit_cost",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="单位成本"
                    ),
                ),
                (
                    "reference_number",
                    models.CharField(
                        blank=True, max_length=30, null=True, verbose_name="参考单号"
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True, verbose_name="备注")),
                (
                    "transaction_time",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="交易时间"
                    ),
                ),
                ("created_by", models.CharField(max_length=50, verbose_name="操作人")),
                (
                    "batch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transactions",
                        to="inventory.inventorybatch",
                        verbose_name="批次",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inventory_transactions",
                        to="product.product",
                        verbose_name="商品",
                    ),
                ),
            ],
            options={
                "verbose_name": "库存交易记录",
                "verbose_name_plural": "库存交易记录",
                "ordering": ["-transaction_time"],
            },
        ),
        migrations.CreateModel(
            name="InventoryCountItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "expected_quantity",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="系统库存量"
                    ),
                ),
                (
                    "actual_quantity",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="实际数量"
                    ),
                ),
                (
                    "difference",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="差异"
                    ),
                ),
                (
                    "notes",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="备注"
                    ),
                ),
                (
                    "inventory_count",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="inventory.inventorycount",
                        verbose_name="盘点单",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="product.product",
                        verbose_name="商品",
                    ),
                ),
            ],
            options={
                "verbose_name": "盘点项目",
                "verbose_name_plural": "盘点项目",
                "unique_together": {("inventory_count", "product")},
            },
        ),
    ]
