# Generated by Django 5.2.1 on 2025-05-26 12:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0001_initial"),
        ("product", "0002_inventorylevel_alter_category_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="inventorybatch",
            options={
                "managed": False,
                "ordering": ["expiry_date", "batch_no"],
                "verbose_name": "库存批次",
                "verbose_name_plural": "库存批次",
            },
        ),
        migrations.AlterModelOptions(
            name="inventorycount",
            options={
                "managed": True,
                "ordering": ["-count_date", "count_number"],
                "verbose_name": "库存盘点",
                "verbose_name_plural": "库存盘点",
            },
        ),
        migrations.AlterModelOptions(
            name="inventorycountitem",
            options={
                "managed": True,
                "verbose_name": "库存盘点项",
                "verbose_name_plural": "库存盘点项",
            },
        ),
        migrations.AlterModelOptions(
            name="inventorytransaction",
            options={
                "managed": True,
                "ordering": ["-transaction_time"],
                "verbose_name": "库存交易",
                "verbose_name_plural": "库存交易",
            },
        ),
        migrations.AlterField(
            model_name="inventorycount",
            name="completed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="inventorycount",
            name="count_date",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="inventorycount",
            name="count_number",
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name="inventorycount",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="inventorycount",
            name="created_by",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="inventorycount",
            name="id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="inventorycount",
            name="notes",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="inventorycount",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "草稿"),
                    ("in_progress", "进行中"),
                    ("completed", "已完成"),
                    ("cancelled", "已取消"),
                ],
                default="draft",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="inventorycountitem",
            name="actual_quantity",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name="inventorycountitem",
            name="difference",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name="inventorycountitem",
            name="expected_quantity",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="inventorycountitem",
            name="id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="inventorycountitem",
            name="inventory_count",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="inventory.inventorycount",
            ),
        ),
        migrations.AlterField(
            model_name="inventorycountitem",
            name="notes",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="inventorycountitem",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="product.product"
            ),
        ),
        migrations.AlterField(
            model_name="inventorytransaction",
            name="batch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="transactions",
                to="inventory.inventorybatch",
            ),
        ),
        migrations.AlterField(
            model_name="inventorytransaction",
            name="created_by",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="inventorytransaction",
            name="id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="inventorytransaction",
            name="notes",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="inventorytransaction",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transactions",
                to="product.product",
            ),
        ),
        migrations.AlterField(
            model_name="inventorytransaction",
            name="quantity",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name="inventorytransaction",
            name="reference_number",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="inventorytransaction",
            name="transaction_time",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="inventorytransaction",
            name="transaction_type",
            field=models.CharField(
                choices=[
                    ("purchase", "采购入库"),
                    ("sales", "销售出库"),
                    ("return", "退货入库"),
                    ("adjustment", "库存调整"),
                    ("transfer", "库存转移"),
                    ("production", "生产"),
                    ("consumption", "消耗"),
                    ("loss", "报损"),
                    ("expiry", "过期"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="inventorytransaction",
            name="unit_cost",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterModelTable(
            name="inventorycount",
            table="inventory_counts",
        ),
        migrations.AlterModelTable(
            name="inventorycountitem",
            table="inventory_count_items",
        ),
        migrations.AlterModelTable(
            name="inventorytransaction",
            table="inventory_transactions",
        ),
    ]
