# Generated by Django 5.2.1 on 2025-05-24 17:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("product", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SalesReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "report_id",
                    models.CharField(max_length=30, unique=True, verbose_name="报告ID"),
                ),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("daily", "日报"),
                            ("weekly", "周报"),
                            ("monthly", "月报"),
                        ],
                        max_length=10,
                        verbose_name="报告类型",
                    ),
                ),
                ("start_date", models.DateField(verbose_name="开始日期")),
                ("end_date", models.DateField(verbose_name="结束日期")),
                (
                    "generated_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="生成时间"),
                ),
            ],
            options={
                "verbose_name": "销售报表",
                "verbose_name_plural": "销售报表",
                "ordering": ["-generated_at"],
            },
        ),
        migrations.CreateModel(
            name="CustomerFlowHeatmap",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="日期")),
                (
                    "hour",
                    models.PositiveSmallIntegerField(
                        help_text="0-23表示一天中的小时", verbose_name="小时"
                    ),
                ),
                (
                    "customer_count",
                    models.IntegerField(default=0, verbose_name="客流量"),
                ),
                (
                    "sales_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="销售额",
                    ),
                ),
            ],
            options={
                "verbose_name": "客流热力图",
                "verbose_name_plural": "客流热力图",
                "ordering": ["-date", "hour"],
                "unique_together": {("date", "hour")},
            },
        ),
        migrations.CreateModel(
            name="MemberRepurchaseRate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="统计日期")),
                (
                    "period_days",
                    models.PositiveSmallIntegerField(verbose_name="统计周期(天)"),
                ),
                (
                    "total_members",
                    models.IntegerField(default=0, verbose_name="总会员数"),
                ),
                (
                    "repurchase_members",
                    models.IntegerField(default=0, verbose_name="复购会员数"),
                ),
                (
                    "repurchase_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        verbose_name="复购率(%)",
                    ),
                ),
            ],
            options={
                "verbose_name": "会员复购率",
                "verbose_name_plural": "会员复购率",
                "ordering": ["-date"],
                "unique_together": {("date", "period_days")},
            },
        ),
        migrations.CreateModel(
            name="TopSellingProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity_sold", models.IntegerField(verbose_name="销售数量")),
                (
                    "total_revenue",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="销售金额"
                    ),
                ),
                ("rank", models.PositiveSmallIntegerField(verbose_name="排名")),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="product.product",
                        verbose_name="商品",
                    ),
                ),
                (
                    "report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="top_products",
                        to="reports.salesreport",
                        verbose_name="关联报表",
                    ),
                ),
            ],
            options={
                "verbose_name": "畅销商品",
                "verbose_name_plural": "畅销商品",
                "ordering": ["report", "rank"],
                "unique_together": {("report", "product")},
            },
        ),
    ]
