# Generated by Django 5.2.1 on 2025-05-24 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CostRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="日期")),
                (
                    "cost_type",
                    models.CharField(
                        choices=[
                            ("ingredients", "原料成本"),
                            ("labor", "人工成本"),
                            ("rent", "租金"),
                            ("utilities", "水电费"),
                            ("marketing", "营销费用"),
                            ("maintenance", "设备维护"),
                            ("misc", "其他费用"),
                        ],
                        max_length=15,
                        verbose_name="成本类型",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="金额"
                    ),
                ),
                ("description", models.CharField(max_length=200, verbose_name="描述")),
                (
                    "reference_number",
                    models.CharField(
                        blank=True, max_length=30, null=True, verbose_name="参考单号"
                    ),
                ),
                ("created_by", models.CharField(max_length=50, verbose_name="创建人")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
            ],
            options={
                "verbose_name": "成本记录",
                "verbose_name_plural": "成本记录",
                "ordering": ["-date", "cost_type"],
            },
        ),
        migrations.CreateModel(
            name="DailyRevenue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(unique=True, verbose_name="日期")),
                (
                    "total_sales",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="总销售额",
                    ),
                ),
                (
                    "total_orders",
                    models.IntegerField(default=0, verbose_name="订单总数"),
                ),
                (
                    "average_order_value",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="平均订单金额",
                    ),
                ),
                (
                    "cash_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="现金金额",
                    ),
                ),
                (
                    "wechat_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="微信金额",
                    ),
                ),
                (
                    "alipay_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="支付宝金额",
                    ),
                ),
                (
                    "card_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="银行卡金额",
                    ),
                ),
                (
                    "member_card_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="会员卡金额",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "每日营业额",
                "verbose_name_plural": "每日营业额",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="ProfitReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "report_id",
                    models.CharField(max_length=30, unique=True, verbose_name="报告ID"),
                ),
                (
                    "period_type",
                    models.CharField(
                        choices=[
                            ("daily", "日报"),
                            ("weekly", "周报"),
                            ("monthly", "月报"),
                            ("quarterly", "季报"),
                            ("yearly", "年报"),
                        ],
                        max_length=10,
                        verbose_name="报告周期",
                    ),
                ),
                ("start_date", models.DateField(verbose_name="开始日期")),
                ("end_date", models.DateField(verbose_name="结束日期")),
                (
                    "total_revenue",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="总收入",
                    ),
                ),
                (
                    "total_cost",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="总成本",
                    ),
                ),
                (
                    "gross_profit",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="毛利润",
                    ),
                ),
                (
                    "net_profit",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="净利润",
                    ),
                ),
                (
                    "profit_margin",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        verbose_name="利润率(%)",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
            ],
            options={
                "verbose_name": "利润报告",
                "verbose_name_plural": "利润报告",
                "ordering": ["-start_date"],
            },
        ),
    ]
