# Generated by Django 5.2.1 on 2025-05-24 17:42

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Staff",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="email address"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "staff_id",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="员工编号"
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("store_manager", "店长"),
                            ("shift_manager", "值班经理"),
                            ("barista", "吧台咖啡师"),
                            ("cashier", "收银员"),
                            ("inventory_keeper", "仓管"),
                        ],
                        max_length=20,
                        verbose_name="角色",
                    ),
                ),
                ("phone", models.CharField(max_length=20, verbose_name="联系电话")),
                (
                    "address",
                    models.TextField(blank=True, null=True, verbose_name="地址"),
                ),
                ("hire_date", models.DateField(verbose_name="入职日期")),
                (
                    "is_active_staff",
                    models.BooleanField(default=True, verbose_name="是否在职"),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "员工",
                "verbose_name_plural": "员工",
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="LoginLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "login_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="登录时间"),
                ),
                (
                    "logout_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="登出时间"
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(verbose_name="IP地址")),
                ("user_agent", models.TextField(verbose_name="浏览器信息")),
                (
                    "is_successful",
                    models.BooleanField(default=True, verbose_name="是否成功"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="login_logs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "登录日志",
                "verbose_name_plural": "登录日志",
                "ordering": ["-login_time"],
            },
        ),
        migrations.CreateModel(
            name="OperationLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "operation_type",
                    models.CharField(
                        choices=[
                            ("create", "创建"),
                            ("update", "更新"),
                            ("delete", "删除"),
                            ("view", "查看"),
                            ("export", "导出"),
                            ("import", "导入"),
                            ("other", "其他"),
                        ],
                        max_length=10,
                        verbose_name="操作类型",
                    ),
                ),
                (
                    "target_model",
                    models.CharField(max_length=50, verbose_name="目标模型"),
                ),
                (
                    "target_id",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="目标ID"
                    ),
                ),
                (
                    "detail",
                    models.TextField(blank=True, null=True, verbose_name="详细信息"),
                ),
                (
                    "operation_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="操作时间"),
                ),
                ("ip_address", models.GenericIPAddressField(verbose_name="IP地址")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="operation_logs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "操作日志",
                "verbose_name_plural": "操作日志",
                "ordering": ["-operation_time"],
            },
        ),
        migrations.CreateModel(
            name="StaffPermission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("store_manager", "店长"),
                            ("shift_manager", "值班经理"),
                            ("barista", "吧台咖啡师"),
                            ("cashier", "收银员"),
                            ("inventory_keeper", "仓管"),
                        ],
                        max_length=20,
                        unique=True,
                        verbose_name="角色",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="描述"),
                ),
                (
                    "permissions",
                    models.ManyToManyField(to="auth.permission", verbose_name="权限"),
                ),
            ],
            options={
                "verbose_name": "角色权限",
                "verbose_name_plural": "角色权限",
            },
        ),
    ]
