# Generated by Django 5.2.1 on 2025-05-26 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user_auth", "0002_permission_role_remove_staff_address_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="operationlog",
            options={
                "managed": False,
                "ordering": ["-timestamp"],
                "verbose_name": "操作日志",
                "verbose_name_plural": "操作日志",
            },
        ),
        migrations.AlterModelOptions(
            name="permission",
            options={
                "managed": False,
                "verbose_name": "权限",
                "verbose_name_plural": "权限",
            },
        ),
        migrations.AlterModelOptions(
            name="role",
            options={
                "managed": False,
                "verbose_name": "角色",
                "verbose_name_plural": "角色",
            },
        ),
        migrations.AlterModelOptions(
            name="rolepermission",
            options={
                "managed": False,
                "verbose_name": "角色权限",
                "verbose_name_plural": "角色权限",
            },
        ),
        migrations.AlterModelOptions(
            name="staff",
            options={
                "managed": False,
                "verbose_name": "员工",
                "verbose_name_plural": "员工",
            },
        ),
    ]
