# Generated by Django 5.2.1 on 2025-05-26 12:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="InventoryLevel",
            fields=[
                (
                    "product",
                    models.OneToOneField(
                        db_column="product_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="product.product",
                    ),
                ),
                (
                    "stock_qty",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("unit", models.CharField(blank=True, max_length=16, null=True)),
                (
                    "reorder_point",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("last_updated", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "库存水平",
                "verbose_name_plural": "库存水平",
                "db_table": "inventory_levels",
                "managed": False,
            },
        ),
        migrations.AlterModelOptions(
            name="category",
            options={
                "managed": False,
                "ordering": ["sort_order", "name"],
                "verbose_name": "商品分类",
                "verbose_name_plural": "商品分类",
            },
        ),
        migrations.AlterModelOptions(
            name="product",
            options={
                "managed": False,
                "ordering": ["name"],
                "verbose_name": "商品",
                "verbose_name_plural": "商品",
            },
        ),
    ]
